### ISSUE TITLE
Score equation visualization

### ISSUE THREAD

**Issue by jingye-xu** [jingye-xu/TinyRunners#5]
Find the best parameters range, use Matlab or python

**Comment by jingye-xu** [comment]
1. Use a new folder to store the results and scripts. 
2. Equation: 
3. $Score = 100* F_\beta + 20 * L_n+ 20* M_n$
4. $F_\beta = {(1+\beta^2) \times {{Precision \times Recall} \over {(\beta^2 \times Precision)+Recall}}}$, where $\beta = 2$
5. $L_n = {1 - {{L - Min_L} \over {Max_L - Min_L}}}$, where $Min_L = 1ms, Max_L = 200ms$
6. $M_n = {1 - {{M - Min_M} \over {Max_M - Min_M}}}$, where $Min_M = 5KiB, Max_M = 256 KiB$
7. Parameters are: $Precision, Recall, L, M$

**Comment by PengKiKi** [comment]
add those into the validation and test process
